server:
  port: ${SERVICE_PORT:8080}

spring:
  profiles:
    active: ${STAGE_NAME:certification}
    group:
      certification: datasources-certification
      staging: datasources-staging
      production: datasources-production
  application:
    name: my-test-example

management:
  health:
    ping:
      enabled: true
    db:
      enabled: false
    defaults:
      enabled: false
  endpoint:
    health:
      show-details: always
      show-components: always

springdoc:
  show-actuator: true

logging:
  level:
    sql: ${SQL_LOGGING_LEVEL:debug}
    org.hibernate.engine.internal.StatisticalLoggingSessionEventListener: ${JPA_SESSION_STATISTICS_LOGGING_LEVEL:OFF}
    com.modyo.example.adapters.restclient: DEBUG
