spring:
  jpa:
    properties:
      hibernate:
        dialect: ${PERSISTENCE_DIALECT:org.hibernate.dialect.MySQLDialect}
        generate_statistics: ${PERSISTENCE_GENERATE_STATISTICS:true}
    hibernate:
      ddl-auto: ${PERSISTENCE_DLL_AUTO:update}
    show-sql: ${PERSISTENCE_SHOW_SQL:false}
  datasource:
    modyo:
      url: ${PERSISTENCE_URL:jdbc:h2:mem:modyo_ms_schema;MODE=MYSQL}
      username: ${PERSISTENCE_USER:root}
      password: ${PERSISTENCE_PASSWORD:}
      ddl-auto: update
      hikari:
        connectionTimeout: ${PERSISTENCE_CONEC_TIMEOUT:30000}
        idleTimeout: ${PERSISTENCE_IDLE_TIMEOUT:600000}
        maxLifetime: ${PERSISTENCE_MAX_LIFETIME:1800000}
        maximumPoolSize: ${PERSISTENCE_MAX_POOL_SIZE:2}
    audit:
      url: ${PERSISTENCE_AUDIT_MODYO_URL:jdbc:h2:mem:audit_ms_schema;MODE=MYSQL}
      username: ${PERSISTENCE_AUDIT_MODYO_USERNAME:root}
      password: ${PERSISTENCE_AUDIT_MODYO_PASSWORD:}
      ddl-auto: update
      hikari:
        connectionTimeout: ${PERSISTENCE_AUDIT_CONEC_TIMEOUT:30000}
        idleTimeout: ${PERSISTENCE_AUDIT_IDLE_TIMEOUT:600000}
        maxLifetime: ${PERSISTENCE_AUDIT_MAX_LIFETIME:1800000}
        maximumPoolSize: ${PERSISTENCE_AUDIT_MAX_POOL_SIZE:1}
